In [ ]:
import numpy as np
import pandas as pd
import sys
import matplotlib

In [44]:
census = pd.read_csv("/content/india-districts-census-2011.csv")
# census.head(2)

In [45]:
cols=['District code','District name','Population','Male','Female','Literate','Households_with_Internet']

In [46]:
census=census[cols]
census.head(2)

,District code,District name,Population,Male,Female,Literate,Households_with_Internet
0,1,Kupwara,870354,474190,396164,439654,762
1,2,Badgam,753745,398041,355704,335649,1999

In [47]:
latlong = pd.read_csv("/content/district wise centroids.csv")
latlong.head()

                 State         District   Latitude  Longitude
0  Andaman and Nicobar  Andaman Islands  12.382571  92.822911
1  Andaman and Nicobar  Nicobar Islands   7.835291  93.511601
2       Andhra Pradesh         Adilabad  19.284514  78.813212
3       Andhra Pradesh        Anantapur  14.312066  77.460158
4       Andhra Pradesh         Chittoor  13.331093  78.927639

In [48]:
final_df=latlong.merge(census,left_on='District',right_on='District name').drop(columns=['District name']).head()
final_df.head(3)

,State,District,Latitude,Longitude,District code,Population,Male,Female,Literate,Households_with_Internet
0,Andhra Pradesh,Adilabad,19.284514,78.813212,532,2741239,1369597,1371642,1483347,5512
1,Andhra Pradesh,Anantapur,14.312066,77.460158,553,4081148,2064495,2016653,2310960,8606
2,Andhra Pradesh,Chittoor,13.331093,78.927639,554,4174064,2090204,2083860,2667878,13763

In [49]:
# this is ratio of female
final_df['sex_ratio']=round((final_df['Female']/final_df['Male'])*100)
final_df.head(1)

,State,District,Latitude,Longitude,District code,Population,Male,Female,Literate,Households_with_Internet,sex_ratio
0,Andhra Pradesh,Adilabad,19.284514,78.813212,532,2741239,1369597,1371642,1483347,5512,100.0

In [50]:
final_df['Literacy_ratio']=round((final_df['Literate']/final_df['Population'])*100)
final_df.head(2)

,State,District,Latitude,Longitude,District code,Population,Male,Female,Literate,Households_with_Internet,sex_ratio,Literacy_ratio
0,Andhra Pradesh,Adilabad,19.284514,78.813212,532,2741239,1369597,1371642,1483347,5512,100.0,54.0
1,Andhra Pradesh,Anantapur,14.312066,77.460158,553,4081148,2064495,2016653,2310960,8606,98.0,57.0

In [51]:
final_df.drop(columns=['Male','Female','Literate'])

,State,District,Latitude,Longitude,District code,Population,Households_with_Internet,sex_ratio,Literacy_ratio
0,Andhra Pradesh,Adilabad,19.284514,78.813212,532,2741239,5512,100.0,54.0
1,Andhra Pradesh,Anantapur,14.312066,77.460158,553,4081148,8606,98.0,57.0
2,Andhra Pradesh,Chittoor,13.331093,78.927639,554,4174064,13763,100.0,64.0
3,Andhra Pradesh,East Godavari,16.782718,82.243207,545,5154296,22411,101.0,64.0
4,Andhra Pradesh,Guntur,15.884926,80.586576,548,4887813,19383,100.0,61.0

In [55]:
final_df.to_csv('Mapp_cleen_data1',index=False)

In [52]:
final_df.to_csv('Mapp_cleen_data')

In [53]:
latlong.isnull().sum()

State        0
District     0
Latitude     0
Longitude    0
dtype: int64

In [54]:
latlong.duplicated().sum()

np.int64(0)